apiVersion: wac-fiit.github.io/v1alpha1
kind: Project
metadata:
  name: vgfiit-ambulance-wl # napr. <pfx>-ambulance-wl
spec:
  title: Zoznam čakajúcich vgfiit # napr. "Zoznam čakajúcich <pfx>"
  description: "Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii" # napr. "Spravuje zoznam pacientov čakajúcich na vyšetrenie v ambulancii"
  authors: "Vladyslav Gusiev" # Zadajte mená autorov
  azureLink: "https://wac-ambulance-vg.azurewebsites.net"
  frontendRepoUrl: "https://github.com/<your-account>/<frontend-repository>"
  backendRepoUrl: "https://github.com/<your-account>/<backend-repository>"
  gitopsRepoUrl: "https://github.com/<your-account>/<gitops-repository>"