apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: vladgusiev/ambulance-wl-webapi
  newName: vladgusiev/ambulance-wl-webapi # {"$imagepolicy":  "wac-hospital:ambulance-webapi:name"}
  newTag: main.20260427.0931 # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
- name: vladgusiev/ambulance-ufe
  newName: vladgusiev/ambulance-ufe # {"$imagepolicy":  "wac-hospital:ambulance-ufe:name"}
  newTag: main.20260323.1010 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
