apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: vgfiit-ambulance-wl
    wac-fiit.github.io/project: vgfiit-ambulance-wl
  includeSelectors: true
  includeTemplates: true
  

resources:
- ../../../apps/vgfiit-ambulance-ufe
- ../../../apps/vgfiit-ambulance-webapi


components:
- ../../../components/version-release