apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: vgfiit-ambulance-ufe-content
spec:
  microFrontend: vgfiit-ambulance-ufe
  element: vgfiit-ambulance-wl-app
  attributes:
    - name: base-path
      value: ./vgfiit-ambulance-wl/
    - name: api-base
      value: http://localhost:5000/api
    - name: ambulance-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?vgfiit-ambulance-wl(/.*)?$"